/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author filip
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setTitle(Application.TITLE_APP + " " + Application.operator.getNameLastName());
        new Time().start();
    }

    private class Time extends Thread {

        private SimpleDateFormat df = new SimpleDateFormat("dd. MM. YYYY. HH:mm:ss");

        @Override
        public void run() {
            while (true) {
                lblTime.setText(df.format(new Date()));
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        lblTime = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmCompany = new javax.swing.JMenuItem();
        jmEmployee = new javax.swing.JMenuItem();
        jmProject = new javax.swing.JMenuItem();
        jmPayment = new javax.swing.JMenuItem();
        jmExit = new javax.swing.JMenuItem();
        jmAboutUs = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        lblTime.setText("Time");
        jToolBar1.add(lblTime);

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jmCompany.setText("Company");
        jmCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCompanyActionPerformed(evt);
            }
        });
        jMenu1.add(jmCompany);

        jmEmployee.setText("Employee");
        jMenu1.add(jmEmployee);

        jmProject.setText("Project");
        jMenu1.add(jmProject);

        jmPayment.setText("Payment");
        jMenu1.add(jmPayment);

        jmExit.setText("Exit");
        jMenu1.add(jmExit);

        jMenuBar1.add(jMenu1);

        jmAboutUs.setText("About us");
        jmAboutUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmAboutUsMouseClicked(evt);
            }
        });
        jmAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAboutUsActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmAboutUs);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 253, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmAboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAboutUsActionPerformed

    }//GEN-LAST:event_jmAboutUsActionPerformed

    private void jmAboutUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAboutUsMouseClicked
        Date d = new Date();
        SimpleDateFormat df = new SimpleDateFormat("YYYY");
        JOptionPane.showMessageDialog(rootPane, " © " + Application.TITLE_APP + " 2020 - " + df.format(d));
    }//GEN-LAST:event_jmAboutUsMouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jmCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCompanyActionPerformed
        new CompanyForm().setVisible(true);
    }//GEN-LAST:event_jmCompanyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu jmAboutUs;
    private javax.swing.JMenuItem jmCompany;
    private javax.swing.JMenuItem jmEmployee;
    private javax.swing.JMenuItem jmExit;
    private javax.swing.JMenuItem jmPayment;
    private javax.swing.JMenuItem jmProject;
    private javax.swing.JLabel lblTime;
    // End of variables declaration//GEN-END:variables
}
